server:
  port: 9090

spring:
  datasource:
    url: jdbc:h2:mem:usersdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none         # schema.sql
    show-sql: true
    properties:
      hibernate.format_sql: true
  sql:
    init:
      mode: always
      platform: h2
  h2:
    console:
      enabled: true
      path: /h2-console

resilience4j:
  retry:
    instances:
      dbOps:
        max-attempts: 3
        wait-duration: 500ms
  circuitbreaker:
    instances:
      dbOps:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
